# Render Blueprint for MOCK IDEA
# This file defines the infrastructure for deploying MOCK IDEA on Render

services:
  # Backend API Service
  - type: web
    name: mock-idea-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: mock-idea-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: mock-idea-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: web
          name: mock-idea-frontend
          property: host
    healthCheckPath: /health

  # Frontend Web Service
  - type: web
    name: mock-idea-frontend
    env: node
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: mock-idea-backend
          property: host

  # AI Service
  - type: web
    name: mock-idea-ai
    env: python
    plan: starter
    buildCommand: cd ai-service && pip install -r requirements.txt
    startCommand: cd ai-service && python main.py
    envVars:
      - key: AI_SERVICE_PORT
        value: 10000
      - key: LOG_LEVEL
        value: INFO

databases:
  # PostgreSQL Database
  - name: mock-idea-db
    plan: starter

  # Redis Cache
  - name: mock-idea-redis
    plan: starter
