version: '3.8'

services:
  ai-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AI_SERVICE_PORT=8000
      - AI_SERVICE_HOST=0.0.0.0
      - LOG_LEVEL=INFO
    volumes:
      - ./models:/app/models
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
